# Generated by Django 4.2 on 2023-05-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "funcionarios",
            "0002_alter_customuser_options_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
